### ISSUE TITLE
Add support for merge keys

### ISSUE THREAD

**Issue by Timothy-Gonzalez** [Timothy-Gonzalez/fsyaml#1]
YAML merge keys, as defined [here](https://yaml.org/type/merge.html) should be supported.

While not part of the standard specification, it is still recommended to support as:
> The use of these tags is not mandatory. However these tags represent types that are useful across a wide range of applications and it is strongly recommended they be used whenever appropriate to promote interoperability.
[Source](https://yaml.org/type/)

This will technically be a breaking change.

# Example Behavior
```yaml
a: &a #Anchor
  b: 1
c: *a #Normal alias
d:
  <<: *a #Merge alias
  e: 2
```
Would result in:
```yaml
a:
  b: 1
c:
  b: 1
d:
  b: 1
  e: 2
```

# Tasks
- [x] Find crate which supports yaml merge keys and integratable support for `serde_yaml`
- [ ] Implement merge keys
- [ ] Create `merge_key` test

**Comment by Timothy-Gonzalez** [comment]
Possible canidate: `yaml_merge_keys`. It even has built-in support for `serde_yaml` through the `serde_yaml` feature.
- [crates.io](https://crates.io/crates/yaml-merge-keys)
- [docs.rs](https://docs.rs/yaml-merge-keys/0.5.1/yaml_merge_keys/)
